
CREATE TABLE IF NOT EXISTS "updated"(
  "FMID" TEXT,
  "MarketName" TEXT,
  "Website" TEXT,
  "Facebook" TEXT,
  "Twitter" TEXT,
  "Youtube" TEXT,
  "OtherMedia" TEXT,
  "street" TEXT,
  "city" TEXT,
  "County" TEXT,
  "State" TEXT,
  "zip" TEXT,
  "Season1Date 1" TEXT,
  "Season1Date 2" TEXT,
  "Season1Time" TEXT,
  "Season2Date 1" TEXT,
  "Season2Time" TEXT,
  "Season3Date 1" TEXT,
  "Season3Time" TEXT,
  "Season4Date 1" TEXT,
  "Season4Time" TEXT,
  "x" TEXT,
  "y" TEXT,
  "Location" TEXT,
  "Credit" TEXT,
  "WIC" TEXT,
  "WICcash" TEXT,
  "SFMNP" TEXT,
  "SNAP" TEXT,
  "Organic" TEXT,
  "Bakedgoods" TEXT,
  "Cheese" TEXT,
  "Crafts" TEXT,
  "Flowers" TEXT,
  "Eggs" TEXT,
  "Seafood" TEXT,
  "Herbs" TEXT,
  "Vegetables" TEXT,
  "Honey" TEXT,
  "Jams" TEXT,
  "Maple" TEXT,
  "Meat" TEXT,
  "Nursery" TEXT,
  "Nuts" TEXT,
  "Plants" TEXT,
  "Poultry" TEXT,
  "Prepared" TEXT,
  "Soap" TEXT,
  "Trees" TEXT,
  "Wine" TEXT,
  "Coffee" TEXT,
  "Beans" TEXT,
  "Fruits" TEXT,
  "Grains" TEXT,
  "Juices" TEXT,
  "Mushrooms" TEXT,
  "PetFood" TEXT,
  "Tofu" TEXT,
  "WildHarvested" TEXT,
  "updateTime" TEXT
);
sqlite>